# Generated by Django 4.2.2 on 2023-08-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_remove_site_id_alter_site_siteid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='ApartmentNumber',
            new_name='Address1',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='HouseNumber',
            new_name='Address2',
        ),
        migrations.RemoveField(
            model_name='site',
            name='Landmark',
        ),
    ]
