# Generated by Django 4.2.4 on 2023-08-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('DOB', models.DateField()),
                ('HouseNumber', models.CharField(max_length=100)),
                ('ApartmentNumber', models.CharField(max_length=100)),
                ('Landmark', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('PIN', models.IntegerField()),
                ('BloodGroup', models.CharField(max_length=100)),
                ('NickName', models.CharField(max_length=100)),
                ('EmergencyNumber', models.IntegerField()),
                ('MatrialStatus', models.CharField(max_length=100)),
                ('DepartmentID', models.CharField(max_length=100)),
                ('TimeZone', models.CharField(max_length=100)),
                ('JoiningDate', models.DateField()),
                ('AboutMe', models.CharField(max_length=100)),
                ('Photo', models.ImageField(upload_to='')),
                ('LegalDocument', models.ImageField(upload_to='')),
                ('Designation', models.CharField(max_length=100)),
            ],
        ),
    ]
