# Generated by Django 4.2.2 on 2023-08-18 16:44

import HR.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_remove_hr_departmentnumber_remove_hr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='Photo',
            field=models.ImageField(),
        ),
    ]
