# Generated by Django 4.2.4 on 2023-08-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('Date', models.DateField()),
                ('Latitude', models.FloatField()),
                ('Longtitude', models.FloatField()),
            ],
        ),
    ]
